### ISSUE TITLE
How to clear Pattern after 5 Second.

### ISSUE THREAD

**Issue by tahsinjawad** [aritraroy/PatternLockView#22]
After Wrong Pattern i can set Pattern color to Red but how can i clear the Pattern after 5 sec when it is wrong. I try Thread to seep 5 sec , it clear the pattern after 5 sec but the color of wrong is not change to red.

**Comment by HarshilVasundhara** [comment]
new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                         mPatternLockView.clearPattern();
     }
}, 5000);

**Put this code when you want**
