### ISSUE TITLE
How to make PLV display error pattern?

### ISSUE THREAD

**Issue by DanteAndroid** [aritraroy/PatternLockView#3]
how to make it recognize the wrong pattern?

**Comment by aritraroy** [comment]
You can make use of the `setViewMode(@PatternViewMode int patternViewMode)` method and use the `WRONG` view mode to display any incorrect pattern. Let me know if you need any more help.

**Comment by DanteAndroid** [comment]
Does that mean I need to call `setViewMode` in `onComplete` and then call `pattern.clear()` myself (If so, I should also delay the clear method)?
I think if there a method `setCorrectPattern(Pattern correct)`, when you set that, after inputting any pattern wrong, then PLV will show error and clear pattern after that.
Thx for your quick reply.

**Comment by aritraroy** [comment]
Yes, exactly. You need to call `setViewMode` after `onComplete()` depending on whether your pattern is correct or wrong. You can also clear the pattern if you want too and add some delay to it as well. 

These kinds of utility methods can be included in the library for quick implementation. I will consider them for future enhancements. Thank you.
