### ISSUE TITLE
Results are not unique

### ISSUE THREAD

**Issue by LLeavesG** [aritraroy/PatternLockView#44]
If i use 4x4 or more dot, the patternlock result will be not unique , such as 12 5 is equal with 1 2 5. So it will be a good idea to use Hex in 4x4 or other encoding in more dot .

**Comment by RicardoCacao** [comment]
Hey king,
I had the same problem happening to me.
I fixed it by overriding the original function that prints the pattern in a list and added a “,” between values.
If you check the original patternToString in “com.andrognito.patternlockview.utils.PatternLockUtils.patternToString” you'll see the code I posted is just that converted to Kotlin and with an added 'append(“,”)'

```
fun patternToString(
    patternLockView: PatternLockView,
    pattern: List<Dot>
): String {
    if (pattern.isEmpty()) {
        return “"
    }
    val patternSize = pattern.size
    val stringBuilder = StringBuilder()
    for (i in 0 until patternSize) {
        val dot = pattern[i]
        stringBuilder.append(dot.row * patternLockView.dotCount + dot.column).append(“,”)
    }
    return stringBuilder.toString()
}
```

**Comment by LLeavesG** [comment]
Yes, you are right. thanks!
