### ISSUE TITLE
how  can i customize ui like this ,thank you

### ISSUE THREAD

**Issue by FaceAISDK** [aritraroy/PatternLockView#9]
![webwxgetmsgimg 2](https://user-images.githubusercontent.com/15169396/27895688-0e3a6d9e-6247-11e7-8f32-b6e262705c81.jpg)

how  can i customize ui like this ,thank you

**Comment by aritraroy** [comment]
Currently, there is no way to achieve this kind of a UI using this library. We will add more customization options later.
